// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV1WUH7vElerXt7TTe36hDugWOnVpUdIs',
    appId: '1:409006645102:web:0a5e8bfd24a0c3a2f56b7f',
    messagingSenderId: '409006645102',
    projectId: 'senecard-aafad',
    authDomain: 'senecard-aafad.firebaseapp.com',
    storageBucket: 'senecard-aafad.appspot.com',
    measurementId: 'G-6953GNR3FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHO47ccnnycXSZUiH-9juRQ61A6s1ycDw',
    appId: '1:409006645102:android:7f844d13d304d5a7f56b7f',
    messagingSenderId: '409006645102',
    projectId: 'senecard-aafad',
    storageBucket: 'senecard-aafad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpDNvolTyPJtGjyRzANaMQ67MiS9xzPV4',
    appId: '1:409006645102:ios:a3f528432463ff79f56b7f',
    messagingSenderId: '409006645102',
    projectId: 'senecard-aafad',
    storageBucket: 'senecard-aafad.appspot.com',
    iosBundleId: 'com.example.senecard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpDNvolTyPJtGjyRzANaMQ67MiS9xzPV4',
    appId: '1:409006645102:ios:a3f528432463ff79f56b7f',
    messagingSenderId: '409006645102',
    projectId: 'senecard-aafad',
    storageBucket: 'senecard-aafad.appspot.com',
    iosBundleId: 'com.example.senecard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV1WUH7vElerXt7TTe36hDugWOnVpUdIs',
    appId: '1:409006645102:web:bb9de5d8a1c43cb0f56b7f',
    messagingSenderId: '409006645102',
    projectId: 'senecard-aafad',
    authDomain: 'senecard-aafad.firebaseapp.com',
    storageBucket: 'senecard-aafad.appspot.com',
    measurementId: 'G-0ZD0N5N5BK',
  );

}